data_path: /Volumes/CrucialX6/Home/projects/EEG-HPC-benchmark
derivatives: true
freqBands:
  Alpha:
    - 8
    - 12
  Beta:
    - 12
    - 30
  Delta:
    - 0.5
    - 4
  Theta:
    - 4
    - 8
method: welch
stepSize: 0.3
windowLength: 3
